# Generated by Django 2.0.3 on 2018-12-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181215_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_post',
            old_name='user',
            new_name='author',
        ),
    ]
