# Generated by Django 2.0.3 on 2018-12-15 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181215_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
