# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feature', '0002_auto_20181219_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='comment',
        ),
        migrations.AddField(
            model_name='feature',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featurecomment',
            name='Feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.Feature'),
        ),
        migrations.AddField(
            model_name='featurecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
