# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0003_auto_20181221_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='subject',
        ),
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=6),
        ),
    ]
