# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0004_auto_20190102_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='upvote',
            new_name='upvotes',
        ),
    ]
