# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0006_auto_20190107_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
