# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature', '0007_auto_20190109_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='purchased',
            field=models.IntegerField(default=0),
        ),
    ]
