# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='user',
        ),
        migrations.AddField(
            model_name='bug',
            name='author',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_by',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
