# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('bug', '0002_auto_20181218_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
