# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_auto_20181221_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Todo', 'To do'), ('Doing', 'Doing'), ('Done', 'Done')], default='Todo', max_length=10),
        ),
    ]
