# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bug', '0006_bug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='assigned',
            field=models.CharField(default='',
                                   max_length=100),
        ),
    ]
