# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bug', '0010_auto_20190104_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'),
                                            ('Done', 'Done')],
                                   default='Todo',
                                   max_length=10),
        ),
    ]
