# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0011_auto_20190104_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugstatus',
            name='bug',
        ),
        migrations.DeleteModel(
            name='BugStatus',
        ),
    ]
