# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bug', '0012_auto_20190215_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Doing', 'Doing'), ('Done', 'Done')], default='Todo',
                                   max_length=10),
        ),
    ]
